src/JcIO.AppModelo/Models/Aluno.cs
namespace JcIO.Site.Models
{
    public class Aluno
    {
        public Aluno()
        {
            Id = Guid.NewGuid();
        }
        public Guid Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public DateTime DataNascimento { get; set; }
    }
}

src/JcIO.AppModelo/Models/Pedido.cs
namespace JcIO.Site.Models
{
    public class Pedido
    {
        public Pedido()
        {
            Id = Guid.NewGuid();
        }
        public Guid Id { get; set; }
    }
}

src/JcIO.AppModelo/Areas/Produtos/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;

namespace JcIO.Site.Areas.Produtos.Controllers
{
    [Area("Produtos")]
    [Route("produtos")]
    public class CadastroController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [Route("buscar")]
        public IActionResult Busca()
        {
            return View();
        }
    }
}

src/JcIO.AppModelo/Areas/Vendas/Controllers/PedidosController.cs
using Microsoft.AspNetCore.Mvc;

namespace JcIO.Site.Areas.Vendas.Controllers
{
    [Area("vendas")]
    public class PedidosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/JcIO.AppModelo/Controllers/HomeController.cs
using JcIO.Site.Data;
using Microsoft.AspNetCore.Mvc;

namespace JcIO.Site.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        public HomeController(IPedidoRepository pedidoRepository)
        {
            _pedidoRepository = pedidoRepository;
        }
        public IActionResult Index()
        {
            var pedido = _pedidoRepository.ObterPedido();
            return View();
        }
    }
}

src/JcIO.AppModelo/Controllers/TesteCrudController.cs
using JcIO.Site.Data;
using JcIO.Site.Models;
using Microsoft.AspNetCore.Mvc;

namespace JcIO.Site.Controllers
{
    public class TesteCrudController : Controller
    {
        private readonly MeuDbContext _context;
        public TesteCrudController(MeuDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var aluno = new Aluno()
            {
                Nome = "Joel",
                DataNascimento = DateTime.Now,
                Email = "joel@email.com"
            };

            _context.Alunos.Add(aluno);
            _context.SaveChanges();

            var aluno2 = _context.Alunos.Find(aluno.Id);
            var aluno3 = _context.Alunos.FirstOrDefault(a => a.Email == "joel@email.com");
            var aluno4 = _context.Alunos.Where(a => a.Nome == "Joel");
            aluno.Nome = "João";

            _context.Alunos.Update(aluno);
            _context.SaveChanges();

            _context.Alunos.Remove(aluno);
            _context.SaveChanges();

            return View();
        }
    }
}

src/JcIO.AppModelo/Areas/Produtos/Views/Cadastro/Busca.cshtml
@{
    ViewData["Title"] = "Busca";
}

<h1>Busca de Produtos</h1>

src/JcIO.AppModelo/Areas/Produtos/Views/Cadastro/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Cadastro de Produtos</h1>

src/JcIO.AppModelo/Areas/Vendas/Views/Pedidos/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Pedidos</h1>

src/JcIO.AppModelo/Views/Home/Index.cshtml
@using JcIO.Site.Data

@inject IPedidoRepository PedidoRepository

Olá! Sou joel

@PedidoRepository.ObterPedido().Id

src/JcIO.AppModelo/Views/Shared/_Layout.cshtml
<html>
<head>
    <title>@ViewData["Title"] - Minha App Modelo</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/site_bundle.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.2/css/bootstrap.min.css"
              integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg=="
              crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <link rel="stylesheet" href="~/lib/font-awesome/css/fontawesome.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppModelo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-converse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Produtos" asp-controller="Cadastro" asp-action="Index">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Vendas" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-auto">
        <div class="container">
            Minha App Modelo - <email email-domain="gmail.com">contato</email> / <email>contato</email>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/js/site_bundle.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" 
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" 
            crossorigin="anonymous" referrerpolicy="no-referrer">
        </script>        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.2/js/bootstrap.min.js"
            integrity="sha512-WW8/jxkELe2CAiE4LvQfwm1rajOS8PHasCCx+knHG0gBHt8EXxS6T6tJRTGuDQVnluuAvMxWF4j8SNFDKceLFg==" 
            crossorigin="anonymous" referrerpolicy="no-referrer">
        </script>
    </environment>
</body>
</html>